### PR TITLE
Upstream Merge

### PR DESCRIPTION
**Pull request by SandPoot**
## About The Pull Request

That's it, pulls stuff from upstream.
## Why It's Good For The Game
Keeping code updated is very good

## Changelog
Check pr contents to know whatever changed

### CODE REVIEW

**Comment by TriggeredBoi** [comment]
nuh uh uh, I ain't removing clock cult. outta here with that.

**Comment by Paisda** [comment]
is the map there too?

**Comment by Paisda** [comment]
WE NEED REEBE

**Comment by SandPoot** [comment]
As if any of you had even played it once there.
If you want support for it go to citadel since they still support it.
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12252

**Comment by Paisda** [comment]
> As if any of you had even played it once there.
> If you want support for it go to citadel since they still support it.
> [Citadel-Station-13/Citadel-Station-13#12252](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12252)

using "how many times someone has been playing on the server to consider their speech as an argument" isnt smart for someone who quit the discord server and stopped playing

**Comment by SandPoot** [comment]
fair enough, good luck for you guys.

**Comment by DeltaFire15** [comment]
Bit late to the party but tellin' people to go play elsewhere because they like to keep one mode in the code that once in a blue moon gets updated ain't the best move to pull. 
Either way y'all have a good day.

**Comment by TriggeredBoi** [comment]
alright yeah you have a point they are pretty broken
breaks my heart to RIP such a unique game mode but it has to be done
I for sure don't have the brains to maintain them, much less alone
image

**Pull request merged**
